### PR TITLE
feat: add weather helpers packages

### PR DESCRIPTION
**Pull request by Swiizyy**

### CODE REVIEW

**Review by favna — APPROVED** [review]
Looks like a 1:1 port of Teryl's code other than just some renames for better clarity, right? LGTM if so

**Comment by Swiizyy** [comment]
Effectivement, c’était 

> Looks like a 1:1 port of Teryl's code other than just some renames for better clarity, right? LGTM if so

It's quite his 👍

**Comment by Swiizyy** [comment]
Do you think that testing this function would be necessary?

**Comment by Swiizyy** [comment]
> Looks like a 1:1 port of Teryl's code other than just some renames for better clarity, right? LGTM if so

I told myself that quite to make a package for twitch and Reddit as much as make one for the weather service

**Review by favna — APPROVED** [review]

**Comment by favna** [comment]
> Do you think that testing this function would be necessary?

that's a no. can't be bothered tbh.

**Pull request merged**
