### PR TITLE
feat: support new select menu types

### PR DESCRIPTION
**Pull request by Bobby-McBobface**
Discord added channel, role, user, mentionable select menus. This pr adds support for these.

### CODE REVIEW

**Review by kyranet — CHANGES_REQUESTED** [review]
Can you run `yarn dedupe` please? And did you also update any other package using the library?

**Comment by Bobby-McBobface** [comment]
> And did you also update any other package using the library?

Sorry, but I don't understand what I need to do to fix that

**Comment by kyranet** [comment]
This:

image

Don't worry, I'm updating it myself while I check if the types are right on my editor.

**Review by kyranet — APPROVED** [review]
I'll approve, but I'll also follow-up to expose `resolved` values on non-string selects:

image

*I'll also include the commit I was supposed to push earlier, can't believe I forgot to hit push...*

**Pull request merged**
